---
- name: Install Katello rpm
  ansible.builtin.command: dnf localinstall -y "http://{{ satellite_fqdn }}/pub/katello-ca-consumer-latest.noarch.rpm"
  changed_when: true

- name: Register against Satellite
  ansible.builtin.command: "{{ item }}"
  loop:
    - subscription-manager register --org="{{ satellite_org_name }}" --activationkey="{{ git_activation_key }}" --force
  changed_when: true

- name: Install packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - policycoreutils
    - openssh-server
    - perl
    - postfix

- name: Start and enable postfix service
  ansible.builtin.service:
    name: postfix
    enabled: true
    state: started

- name: Download script
  ansible.builtin.get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.rpm.sh
    dest: ~/script.rpm.sh
    mode: '0755'

- name: Execute script
  ansible.builtin.shell: |
    set -o pipefail
    ~/script.rpm.sh
  register: res

- name: print script execution output for debug
  debug:
    var: res

- name: Install GitLab-EE
  environment:
    EXTERNAL_URL: "http://{{ git_fqdn }}"
    GITLAB_ROOT_PASSWORD: "{{ git_root_password }}"
  ansible.builtin.dnf:
    name: gitlab-ee
    state: present
