apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: default-storage-class
  namespace: {{ .Values.odf.namespace }}
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.global.params.job_image }}
        env:
          - name: SLEEP
            value: "3"
        command:
        - /bin/bash
        - -c
        - |
          echo "Wait for RBD storage class to be available"
          DEFAULT_CLASS=ocs-storagecluster-ceph-rbd

          RBD_CLASS="Pausing $SLEEP seconds..."
          while [ "$RBD_CLASS" != "$DEFAULT_CLASS" ]; do
            echo "Waiting for the RBD Storage Class to be ready. ($RBD_CLASS)"
            sleep $SLEEP
            RBD_CLASS=$( oc get storageclass $DEFAULT_CLASS | egrep $DEFAULT_CLASS | awk '{print $1}' )
            echo "RBD_CLASS is $RBD_CLASS"
          done
          oc patch storageclass $DEFAULT_CLASS -p '{"metadata": {"annotations": {"storageclass.kubernetes.io/is-default-class": "true"}}}'
          echo "All done! Hooray!"
        name: default-storage-class-rbd
        resources: {}  
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: {{ .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      terminationGracePeriodSeconds: {{ .Values.odf.jobTerminationGracePeriod }}




