#apiVersion: ocs.openshift.io/v1
#kind: StorageCluster
#metadata:
#  namespace: {{ .Values.odf.namespace }}
#  name: ocs-storagecluster
#spec:
#  resources:
#    mon:
#      requests:
#        cpu: {{ .Values.odf.mon.requests.cpu | squote }}
#        memory: {{ .Values.odf.mon.requests.memory }}
#    mds:
#      requests:
#        cpu: {{ .Values.odf.mds.requests.cpu | squote }}
#        memory: {{ .Values.odf.mds.requests.memory }}
#    mgr:
#      requests:
#        cpu: {{ .Values.odf.mgr.requests.cpu | squote }}
#        memory: {{ .Values.odf.mgr.requests.memory }}
#    noobaa-core:
#      requests:
#        cpu: {{ .Values.odf.noobaacore.requests.cpu | squote }}
#        memory: {{ .Values.odf.noobaacore.requests.memory }}
#    noobaa-db:
#      requests:
#        cpu: {{ .Values.odf.noobaadb.requests.cpu | squote }}
#        memory: {{ .Values.odf.noobaadb.requests.memory }}
#  storageDeviceSets:
#  - name: ocs-deviceset
#    config: {}
#    count: 1
#    replica: 3
#    resources:
#      requests:
#        cpu: {{ .Values.odf.osd.requests.cpu | squote }}
#        memory: {{ .Values.odf.osd.requests.memory }}
#    placement: {}
#    preparePlacement: {}
#    dataPVCTemplate:
#      metadata: {}
#      spec:
#        storageClassName: {{ .Values.global.datacenter.storageClassName }}
#        accessModes:
#        - ReadWriteOnce
#        volumeMode: Block
#        resources:
#          requests:
#            storage: {{ .Values.odf.osd.pvc.storage }}
#      status: {}
#    portable: true
#
#
#
#
#
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  arbiter: {}
  encryption:
    kms: {}
  externalStorage: {}
  flexibleScaling: false
  resources:
    mds:
      limits:
        cpu: "3"
        memory: "8Gi"
      requests:
        cpu: "3"
        memory: "8Gi"
  monDataDirHostPath: /var/lib/rook
  managedResources:
    cephBlockPools:
      reconcileStrategy: manage   # <-- Default value is manage
    cephConfig: {}
    cephFilesystems: {}
    cephObjectStoreUsers: {}
    cephObjectStores: {}
  multiCloudGateway:
    reconcileStrategy: manage   # <-- Default value is manage
  storageDeviceSets:
  - count: 2 
    dataPVCTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "1"
        storageClassName: localblock
        volumeMode: Block
    name: ocs-deviceset
    placement: {}
    portable: false
    replica: 3
    resources:
      limits:
        cpu: "2"
        memory: "5Gi"
      requests:
        cpu: "2"
        memory: "5Gi"
    
