




---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    argocd.argoproj.io/instance: mc
  name: openshift-performance-addon-operator

    

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-performance-addon-operator
  namespace: openshift-performance-addon-operator

---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-performance-addon-operator-subscription
  namespace: openshift-performance-addon-operator
spec:
  channel: "4.10"
  name: performance-addon-operator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace





    #---
    #apiVersion: performance.openshift.io/v2
    #kind: PerformanceProfile
    #metadata:
    #  name: systemreservedset
    #  annotations:
    #    kubeletconfig.experimental: |
    #      {"allowedUnsafeSysctls":["net.core.somaxconn"]}
    #spec:
    #  cpu:     
    #    reserved: 0-3,8-15
    #    isolated: 4-7
    #  nodeSelector:
    #    node-role.kubernetes.io/master: ""
    #
    #
    #
