---
apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: systemreservedset-worker
  annotations:
    kubeletconfig.experimental: |
      {"systemReserved": {"cpu": "8000m","memory": "16Gi"},
       "kubeReserved":{"cpu": "8000m","memory": "16Gi"}}
spec:
  cpu:     
    reserved: 0-3,72-75
    isolated: 4-71,76-143
  nodeSelector:
    node-role.kubernetes.io/worker: ""

