apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: mgnt-kafka
  annotations:
    metallb.universe.tf/address-pool: default
    argocd.argoproj.io/sync-wave: "2"
  namespace: kafka-cluster
spec:
  kafka:
    config:
      auto.create.topics.enable: false
      default.replication.factor: 1
      inter.broker.protocol.version: '3.5'
      message.max.bytes: 369295618
      min.insync.replicas: 1
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    storage:
      volumes:
        - class: ocs-storagecluster-ceph-rbd
          deleteClaim: true
          id: 0
          size: '50Gi'
          type: persistent-claim
      type: jbod
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: tls
        port: 9093
        tls: true
        type: internal
      - name: external
        port: 9094
        tls: true
        type: route
    replicas: 3
    version: 3.5.0
  entityOperator:
    topicOperator: {}
    userOperator: {}
  zookeeper:
    storage:
      class: ocs-storagecluster-ceph-rbd
      deleteClaim: true
      size: '40Gi'
      type: persistent-claim
    replicas: 3


