---
- name: Create resource defined in {{ src }}
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    username: "{{ rhocp_user }}"
    password: "{{ rhocp_password }}"
    state: present
    template:
      path: "{{ src }}"
  retries: 5
  delay: 10
  until: not result.failed
  register: result

- name: Debug the result of the create resource task in case of failure
  ansible.builtin.debug:
    var: result
  when: result.failed
