---
global:
  xraylab:
    namespace: "openshift-local-storage"
  datacenter:
    storageClassName: gp2
    region: us-east-1


lso:
  jobTerminationGracePeriod: 300
  namespace: openshift-local-storage


#RoleBasedAccessControl
serviceAccountName: lso-node-label-sa
rbac:
  roles:
    - name: label-storage-nodes
      createRole: true
      apiGroups:
        - '""'
      scope:
        cluster: true
      resources:
        - nodes
      verbs:
        - "get"
        - "list"
        - "patch"
        - "update"
    - name: edit-storageclass
      createRole: true
      apiGroups:
        - 'storage.k8s.io'
      scope:
        cluster: true
      resources:
        - storageclasses 
      resourceNames:
        - ocs-storagecluster-ceph-rbd
      verbs:
        - "get"
        - "list"
        - "patch"
        - "update"
  roleBindings:
    - name: label-storage-nodes
      createBinding: true
      scope:
        cluster: true
        namespace: ""
      subjects:
        kind: ServiceAccount
        name: lso-node-label-sa
        namespace: openshift-local-storage
        apiGroup: ""
      roleRef:
        kind: ClusterRole
          # name: label-storage-nodes
        name: cluster-admin
    - name: edit-storageclass
      createBinding: true
      scope:
        cluster: true
        namespace: ""
      subjects:
        kind: ServiceAccount
        name: lso-node-label-sa
        namespace: openshift-local-storage
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: edit-storageclass

job:
  image: registry.redhat.io/openshift4/ose-cli:latest 
