apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mgmt.quay.configBundleSecret.name }}
  namespace: {{ .Values.mgmt.quay.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
type: Opaque
stringData:
  config.yaml: |
    {{- range $key, $val := .Values.mgmt.quay.param }}
    {{ $key }}: {{ $val }}
    {{- end }}
    
