apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: nad-br-apps
  namespace: mgmt-apps
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  config: '{ 
    "cniVersion": "0.3.1", 
    "name": "nad-br-apps", 
    "type": "bridge",
    "bridge": "br-apps",  
    "ipam": { 
      "type": "static",
      "addresses": [ { "address": "{{ .Values.mgmt.apps_subnet }}/{{ .Values.mgmt.apps_subnet_len }}" } ] 
      },
    "capabilities": { "ips": true }
    }'
